### ISSUE TITLE
Cannot find module '@babel/runtime/helpers/interopRequireDefault'

### ISSUE THREAD

**Issue by neiker** [NullVoxPopuli/optional-chaining-codemod#3]
```bash
npx @nullvoxpopuli/optional-chaining-codemod ./src/app.tsx 

npx: installed 407 in 12.347s
Processing 1 files... 
Spawning 1 workers...
Sending 1 files to free worker...
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'
Require stack:
- /Users/{user}/.npm/_npx/69724/lib/node_modules/@nullvoxpopuli/optional-chaining-codemod/node_modules/fs-extra/lib/index.js
- /Users/{user}/.npm/_npx/69724/lib/node_modules/@nullvoxpopuli/optional-chaining-codemod/node_modules/codemod-cli/src/test-support.js
- /Users/{user}/.npm/_npx/69724/lib/node_modules/@nullvoxpopuli/optional-chaining-codemod/node_modules/codemod-cli/src/index.js
- /Users/{user}/.npm/_npx/69724/lib/node_modules/@nullvoxpopuli/optional-chaining-codemod/transforms/optional-chaining/index.js
- /Users/{user}/.npm/_npx/69724/lib/node_modules/@nullvoxpopuli/optional-chaining-codemod/node_modules/jscodeshift/src/Worker.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/{user}/.npm/_npx/69724/lib/node_modules/@nullvoxpopuli/optional-chaining-codemod/node_modules/fs-extra/lib/index.js:1:41)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Module._compile (/Users/{user}/.npm/_npx/69724/lib/node_modules/@nullvoxpopuli/optional-chaining-codemod/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Object.newLoader [as .js] (/Users/{user}/.npm/_npx/69724/lib/node_modules/@nullvoxpopuli/optional-chaining-codemod/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:641:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/{user}/.npm/_npx/69724/lib/node_modules/@nullvoxpopuli/optional-chaining-codemod/node_modules/fs-extra/lib/index.js',
    '/Users/{user}/.npm/_npx/69724/lib/node_modules/@nullvoxpopuli/optional-chaining-codemod/node_modules/codemod-cli/src/test-support.js',
    '/Users/{user}/.npm/_npx/69724/lib/node_modules/@nullvoxpopuli/optional-chaining-codemod/node_modules/codemod-cli/src/index.js',
    '/Users/{user}/.npm/_npx/69724/lib/node_modules/@nullvoxpopuli/optional-chaining-codemod/transforms/optional-chaining/index.js',
    '/Users/{user}/.npm/_npx/69724/lib/node_modules/@nullvoxpopuli/optional-chaining-codemod/node_modules/jscodeshift/src/Worker.js'
  ]
}
All done. 
Results: 
0 errors
0 unmodified
0 skipped
0 ok
Time elapsed: 0.917seconds 
```

Tell me if you need more info :)

**Comment by NullVoxPopuli** [comment]
yeah, I just tested this myself on a .ts file, and it worked fine. I wonder if it's specific to .tsx?

can you provide a sample tsx that can be added to the test fixtures folder?

**Comment by neiker** [comment]
I replaced all the file content with this and still having the same error:

```tsx
const lala = {};

if (lala && lala.la && lala.la.po) {
  console.log('');
}
```

More info:

```bash
System:
    OS: macOS 10.15
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 94.61 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.3.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmGlobalPackages:
    react-native-asset: 2.0.0
    react-native-cli: 2.0.1
```

**Comment by NullVoxPopuli** [comment]
Hm, I only have Linux to test this on. Any chance you could dig in?

**Comment by neiker** [comment]
Not right now, but I have add a reminder to take a look later.

**Comment by NullVoxPopuli** [comment]
thanks <3
